[package]
name = "avoision_game"
version = "0.1.0"
authors = ["Paul Young"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
rand = "0.8.4"